server:
  port: 8081
  contextPath: "/messaging-service"

log:
  level: "debug"

producer:
  primary:
    name: "KafkaLocal"
    enabled: true
    fastFail: true
    producerConfig:
      type: "kafka"
      kafkaConfig:
        healthCheckTopic: "health"
        brokers:
          - "localhost:9094"
  fallback:
    name: "KafkaStage"
    enabled: true
    fastFail: true
    producerConfig:
      type: "kafka"
      kafkaConfig:
        healthCheckTopic: "health"
        brokers:
          - "my-cluster-broker-0.my-cluster-kafka-brokers.kafka.svc:9094"
