// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"shopdeck.com/messaging_service/app/controller"
	"shopdeck.com/messaging_service/app/service"
)

// Injectors from injector.go:

func Init() *Initialization {
	kafkaMessageService := service.KafkaMessageServiceInit()
	defaultMessageServiceImpl := service.DefaultMessageServiceInit(kafkaMessageService)
	messageControllerImpl := controller.MessageControllerInit(defaultMessageServiceImpl)
	initialization := NewInitialization(defaultMessageServiceImpl, messageControllerImpl)
	return initialization
}

// injector.go:

// MessageService
var kafkaMessageServiceSet = wire.NewSet(service.KafkaMessageServiceInit)

var defaultMessageServiceSet = wire.NewSet(service.DefaultMessageServiceInit, wire.Bind(new(service.MessageService), new(*service.DefaultMessageServiceImpl)))

// Message Controller
var messageControllerSet = wire.NewSet(controller.MessageControllerInit, wire.Bind(new(controller.MessageController), new(*controller.MessageControllerImpl)))
